# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Huddle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Huddle

	pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
    
    pod 'Fabric'
    pod 'Crashlytics'

	pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
	pod 'React', :path => '../node_modules/react-native', :subspecs => [
	  'BatchedBridge',
	  'Core',
	]

  target 'HuddleTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Fabric'
    pod 'Crashlytics'
  end


end

target 'Huddle-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Huddle-tvOS

  target 'Huddle-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

